


spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/pocket?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          header: Authorization
#          secret: mySecret
#          expiration: 60
#          issuer-uri:



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



mybatis:
  type-aliases-package: com.pocket.Data
  mapper-locations: classpath:Mapper/*Mapper.xml

